### PR TITLE
fixed id_encode_array() and small refactoring

### PR DESCRIPTION
**Pull request by dwagin**

### CODE REVIEW

**Comment by iCyberon** [comment]
Awesome job @dwagin, can you bump the version to `1.3.0`?

**Comment by dwagin** [comment]
> Awesome job @dwagin, can you bump the version to `1.3.0`?

Good idea!

Another question, can I change the code style to [FreeBSD style](https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9)?

**Comment by iCyberon** [comment]
> Another question, can I change the code style to [FreeBSD style](https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9)?

Sure, go ahead. But it might be a good idea to create another PR for the style change

**Comment by iCyberon** [comment]
Thanks @dwagin, really appreciate it 👍

**Pull request merged**
